---
title: "data_clean"
author: "Brad Cannell"
date: "May 4, 2016"
output: html_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```

**Load Packages**
```{r message=FALSE}
library(rprojroot)
library(data.table)
library(readxl)
```

**Import Data**   
```{r}
# Root directory
root <- rprojroot::find_root("DESCRIPTION")

# Pilot screener responses
fpath <- paste0(root, "/inst/extdata/pilot_data_2015_10_27.csv")
detectpt <- data.table::fread(fpath)

# Pilot reports to APS
fpath <- paste0(root, "/inst/extdata/DETECT_APS Data_110515.xlsx")
detectptreports <- data.table::setDT(readxl::read_excel(fpath))
```
------   

&nbsp;   

# Clean Pilot Screener Responses

**Recode Data**   
Recode "NULL" to NA and convert "Yes" and "No" to numeric.
```{r}
# Recode values
detectpt <- data.table::setDT(lapply(detectpt, function(x){
  x[x == "NULL"] <- NA
  x[x == "Dont Know"] <- 9L
  x[x == "No"] <- 0L
  x[x == "Yes"] <- 1L
  x <- as.integer(x)
  return(x)
}))
```

**Flatten out the data set so that I only have one row per incident ID.**   
Currently the data is structured with 26 rows per incident ID (one for each screening item), with only one non-missing value per row. Every other value in each row is an NA.   

Collapse all the rows for each incident ID into a single row with a non-missing value for each screening item (where possible).
```{r warning=FALSE}
# Collapse rows
detectpt <- detectpt[, lapply(.SD, max, na.rm = TRUE), by = incidentID]

# Recode -Inf to NA
detectpt <- data.table::setDT(lapply(detectpt, function(x){
  x[is.infinite(x)] <- NA
  return(x)
}))
```

**Convert Screening Questions to Factors**
```{r}
temp <- data.table::setDT(lapply(detectpt[, .SD, .SDcol = -1], factor, 
  levels = c(0, 1, 9),
  labels = c("No", "Yes", "Don't Know")))
detectpt <- cbind(detectpt[, .(incidentID)], temp)
rm(temp)
```

**Data Info**
```{r echo=FALSE}
data_info <- function(x){
  cat("Data Set:", deparse(substitute(x)), "\n")
  cat("Class:", class(x), "\n")
  cat(nrow(x), "Rows and", ncol(x), "Variables", "\n")
  cat("Variable Names:", "\n")
  names(x)
}
data_info(detectpt)
```

**Save Data**
```{r}
save(detectpt, file = paste0(root, "/data/detectpt.RData"))
```
------   

&nbsp;

# Clean Reports to APS   

**Rename Variables**
```{r}
names(detectptreports) <- c("agency", "confirmation_number", "report_date", "e_report", "response_number")
```

**Subset the Data**
```{r}
# Keep reports to APS only
detectptreports <- detectptreports[agency == "APS"]

# Drop confirmation number
detectptreports <- detectptreports[, .SD, .SDcol = -2]

# Number of reports
nrow(detectptreports)
```

Unfortunately, there is currently no way to link these reports with the screener responses.   

-----

#### Session Info:
```{r echo=FALSE}
sessionInfo()
```
